### ISSUE TITLE
Activity log error when opening VS 2017 community

### ISSUE THREAD

**Issue by GregTrevellick** [onlyutkarsh/AzureDevOpsStatusMonitor#14]
Hi Utkarsh,

I installed your vsix but when I opened VS2017 it showed me the error pop-up window and I had the following error in my activity log:

SetSite failed for package [AzureDevOpsStatusMonitorPackage]Source:  'AzureDevOpsStatusMonitor' Description: Could not load file or assembly  'Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral,  PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot  find the file specified. System.IO.FileNotFoundException: Could not load file or  assembly 'Microsoft.VisualStudio.Threading, Version=15.8.0.0, Culture=neutral,  PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot  find the file specified. File name: 'Microsoft.VisualStudio.Threading,  Version=15.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at  AzureDevOpsStatusMonitor.AzureDevOpsStatusMonitorPackage.InitializeAsync(CancellationToken  cancellationToken, IProgress`1 progress) at  Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()  --- End of stack trace from previous location where exception was thrown --- at  Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at  Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean  ignoreUIThreadCheck) at Microsoft.VisualStudio.Services.VsTask.GetResult() WRN:  Assembly binding logging is turned OFF. To enable assembly bind failure logging,  set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.  Note: There is some performance penalty associated with assembly bind failure  logging. To turn this feature off, remove the registry value  [HKLM\Software\Microsoft\Fusion!EnableLog].
--

Can I supply any other info to help ? If I get time I'll try to run the repo locally and debug in experimental instance.

Greg

**Comment by onlyutkarsh** [comment]
@GregTrevellick Thank you for raising this issue. Will try to investigate soon.

**Comment by onlyutkarsh** [comment]
@GregTrevellick can you try this version? If it works for you I will push to `master`. There are some issues with VS2015 but fixes issues in VS 2017. I tried on VS 2017 Community.

[AzureDevOpsStatusMonitor.zip](https://github.com/onlyutkarsh/AzureDevOpsStatusMonitor/files/2637483/AzureDevOpsStatusMonitor.zip)

**Comment by GregTrevellick** [comment]
Hi Utkarsh - I uninstalled the version I installed from the marketplace, and then had problems starting the IDE (it started ok but the cursor stuck on spinning circle, it may have cleared if I left it a while but I didn't wait to see). At this point I realised I was using 15.6.1 so I tried the marketplace version on another PC using 15.9.3 and it worked fine. So I updated my PC with 15.6 to 15.9 and it now works fine. So in the end I didn't try the zip version as the marketplace version works now I updated to 15.9.3. Thanks anyway, Greg

**Comment by onlyutkarsh** [comment]
Great! thanks for letting me know. I also pushed a fix to the marketplace this morning to use the older VS assemblies so that they are automatically redirected to versions installed on the user machine. Will probably make it work on different VS versions (with older assemblies) now.
